# For more information: https://laravel.com/docs/sail
version: '3'
services:
    backend:
        build:
            context: ./backend/docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './backend:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'MySQLPass'
            MYSQL_DATABASE: 'adChecker'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'MySQLPass'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    frontend:
        image: node:lts-alpine
        ports:
            - '8080:8080'
        volumes:
            - ./frontend/:/srv/app
        networks:
            - sail
        working_dir: /srv/app
        command: 'yarn serve'
    ml.service:
        build:
            context: ./ml
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - './ml:/app'
        networks:
            - sail
        depends_on:
            - mysql
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
